# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "genawaiter"
version = "0.2.2"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"
license = "MIT"
description = "Stackless generators on stable Rust."
repository = "https://github.com/whatisaphone/genawaiter"
documentation = "https://docs.rs/genawaiter"
readme = "README-crates-io.md"
keywords = ["generator", "yield", "coroutine", "async", "await"]
categories = ["asynchronous", "concurrency", "rust-patterns"]
include = ["Cargo.toml", "README-crates-io.md", "src/**/*.rs"]

[dependencies]
futures-core = { version = "0.3.1", optional = true }
genawaiter_proc_macro = { path = "./genawaiter_proc_macro" } #optional = true

[workspace]
members = [ "genawaiter_proc_macro" ]

[dev-dependencies]
futures = "0.3.1"

[features]
futures03 = ["futures-core"]
nightly = []
strict = []
# proc_macro = ["genawaiter_proc_macro"]
