# https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: CI
on: push

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-11-06
          profile: minimal
          components: rustfmt
          override: true
      - run: cargo fmt -- --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.39.0
          profile: minimal
          components: clippy
          override: true
      - run: cargo clippy --all-targets --features strict

  test:
    strategy:
      matrix:
        toolchain: [1.39.0, nightly-2019-11-06]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - run: cargo test
